### ISSUE TITLE
add final signatures

### ISSUE THREAD

**Issue by grst** [grst/fantom5-sig#3]
@Accio, can you upload the final `gmt` file here? 
Or what would be the place to  publish it?

**Comment by Accio** [comment]
Done in commit 91e6b50b5dc3f1c7425fbb19fb4769edd3c2cbfe.

I found two sets of signatures: one including all tissues and apparently a subset of cell-line and primary-cell signatures, and another including only HQ signatures of primary cell types. For the analysis of the paper, I only used HQ signatures. 

Please also double-check the thresholds. I think the values stated in the texts now do not match 100% with the values found in gmt files.

Thanks!
